python extract2.py ./text/40_R4_saiwaicho.txt
python extract2.py ./text/78_R4_roppongi.txt
python extract2.py ./text/106_R4_sakurajuji.txt
python extract2.py ./text/57_R4_mimuro.txt
python extract2.py ./text/39_R4_kyourin.txt
python extract2.py ./text/113_R4_sanchaart.txt
python extract2.py ./text/53_R4_shibakamiyama.txt
python extract2.py ./text/109_R4_kokubunji.txt
python extract2.py ./text/17_R4_nichii.txt
python extract2.py ./text/36_R4_usui.txt
python extract2.py ./text/20_R4_ikashika.txt
python extract2.py ./text/114_R4_ikuryo.txt
python extract2.py ./text/1_R4_hamada.txt
python extract2.py ./text/21_R4_ai.txt
python extract2.py ./text/100_R4_kitasato.txt
python extract2.py ./text/6_R4_harune.txt
python extract2.py ./text/65_R4_ezaki.txt
python extract2.py ./text/79_R4_kyounoart-takanawa.txt
python extract2.py ./text/45_R4_teikyo.txt
python extract2.py ./text/59_tokuoka_20230701ver2.txt
python extract2.py ./text/76_R4_kaibara.txt
python extract2.py ./text/60_R4_utsumiyasuko.txt
python extract2.py ./text/16_R4_kato.txt
python extract2.py ./text/97_R4_akihabara.txt
python extract2.py ./text/107_R4_Asada9gou.txt
python extract2.py ./text/94_R4_azabu.txt
python extract2.py ./text/69_R4_hiroi.txt
python extract2.py ./text/74_R4_shinjukuart.txt
python extract2.py ./text/29_R4_fatility.txt
python extract2.py ./text/87_R4_c-ange.txt
python extract2.py ./text/14_R4_keio.txt
python extract2.py ./text/56_R4_usuda.txt
python extract2.py ./text/63_R4_gonohashi.txt
python extract2.py ./text/99_R4_mine.txt
python extract2.py ./text/43_R4_inoue.txt
python extract2.py ./text/110_R4_tokyoamh.txt
python extract2.py ./text/115_R4_kanda.txt
python extract2.py ./text/81_R4_denentoshi.txt
python extract2.py ./text/5_R4_ginzaladies.txt
python extract2.py ./text/27_R4_umegaoka.txt
python extract2.py ./text/80_R4_keiai.txt
python extract2.py ./text/19_R4_toudai.txt
python extract2.py ./text/96_R4_ripuro.txt
python extract2.py ./text/83_R4_rose.txt
python extract2.py ./text/103_R4_megumi.txt
python extract2.py ./text/38_R4_majima.txt
python extract2.py ./text/66_R4_tokiwadai.txt
python extract2.py ./text/117_R4_ebisutsuji.txt
python extract2.py ./text/67_R4_niji-ogikubo.txt
python extract2.py ./text/49_R4_nakano.txt
python extract2.py ./text/30_R4_hara.txt
python extract2.py ./text/68_R4_ikeshita.txt
python extract2.py ./text/85_R4_kokusaiiryou.txt
python extract2.py ./text/104_R4_nihonbashi.txt
python extract2.py ./text/102_R4_ginzakounotori.txt
python extract2.py ./text/35_R4_nichidaiitabashi.txt
python extract2.py ./text/77_R4_morozumi.txt
python extract2.py ./text/62_R4_shinbashiyume.txt
python extract2.py ./text/98_R4_sakuranome.txt
python extract2.py ./text/72_R4_sanchawomens.txt
python extract2.py ./text/101_R4_komachi.txt
python extract2.py ./text/92_R4_akasaka.txt
python extract2.py ./text/47_R4_tohofujin.txt
python extract2.py ./text/23_R4_syouwa.txt
python extract2.py ./text/46_R4_jinnno.txt
python extract2.py ./text/13_R4_tokyoika.txt
python extract2.py ./text/48_R4_ginzasuzuran.txt
python extract2.py ./text/24_R4_toho.txt
python extract2.py ./text/90_R4_naturalart.txt
python extract2.py ./text/54_R4_ooizumigakuen.txt
python extract2.py ./text/10_R4_sannou.txt
python extract2.py ./text/12_R4_akasakamiyazaki.txt
python extract2.py ./text/18_R4_juntendou.txt
python extract2.py ./text/107_R4_Asada10gou.txt
python extract2.py ./text/8_R4_toranomon.txt
python extract2.py ./text/93_R4_jounan.txt
python extract2.py ./text/25_R4_cinemaart.txt
python extract2.py ./text/84_R4_aidakibo.txt
python extract2.py ./text/82_R4_kusuhara.txt
python extract2.py ./text/28_R4_tokyohart.txt
python extract2.py ./text/9_R4_jikei.txt
python extract2.py ./text/15_R4_tokyojoshi.txt
python extract2.py ./text/119_R4_esset.txt
python extract2.py ./text/107_Asada_besshi.txt
python extract2.py ./text/89_R4_iwamoto.txt
python extract2.py ./text/42_R4_sugiyamashinjuku.txt
python extract2.py ./text/34_R4_matsumoto.txt
python extract2.py ./text/73_R4_sugiyamamarunouchi.txt
