pdftotext -raw -layout -nopgbrk ./mydir/63_R4_gonohashi.pdf ./text/63_R4_gonohashi.txt
pdftotext -raw -layout -nopgbrk ./mydir/99_R4_mine.pdf ./text/99_R4_mine.txt
pdftotext -raw -layout -nopgbrk ./mydir/43_R4_inoue.pdf ./text/43_R4_inoue.txt
pdftotext -raw -layout -nopgbrk ./mydir/87_R4_c-ange.pdf ./text/87_R4_c-ange.txt
pdftotext -raw -layout -nopgbrk ./mydir/56_R4_usuda.pdf ./text/56_R4_usuda.txt
pdftotext -raw -layout -nopgbrk ./mydir/14_R4_keio.pdf ./text/14_R4_keio.txt
pdftotext -raw -layout -nopgbrk ./mydir/80_R4_keiai.pdf ./text/80_R4_keiai.txt
pdftotext -raw -layout -nopgbrk ./mydir/19_R4_toudai.pdf ./text/19_R4_toudai.txt
pdftotext -raw -layout -nopgbrk ./mydir/96_R4_ripuro.pdf ./text/96_R4_ripuro.txt
pdftotext -raw -layout -nopgbrk ./mydir/83_R4_rose.pdf ./text/83_R4_rose.txt
pdftotext -raw -layout -nopgbrk ./mydir/103_R4_megumi.pdf ./text/103_R4_megumi.txt
pdftotext -raw -layout -nopgbrk ./mydir/110_R4_tokyoamh.pdf ./text/110_R4_tokyoamh.txt
pdftotext -raw -layout -nopgbrk ./mydir/115_R4_kanda.pdf ./text/115_R4_kanda.txt
pdftotext -raw -layout -nopgbrk ./mydir/81_R4_denentoshi.pdf ./text/81_R4_denentoshi.txt
pdftotext -raw -layout -nopgbrk ./mydir/5_R4_ginzaladies.pdf ./text/5_R4_ginzaladies.txt
pdftotext -raw -layout -nopgbrk ./mydir/27_R4_umegaoka.pdf ./text/27_R4_umegaoka.txt
pdftotext -raw -layout -nopgbrk ./mydir/114_R4_ikuryo.pdf ./text/114_R4_ikuryo.txt
pdftotext -raw -layout -nopgbrk ./mydir/1_R4_hamada.pdf ./text/1_R4_hamada.txt
pdftotext -raw -layout -nopgbrk ./mydir/21_R4_ai.pdf ./text/21_R4_ai.txt
pdftotext -raw -layout -nopgbrk ./mydir/100_R4_kitasato.pdf ./text/100_R4_kitasato.txt
pdftotext -raw -layout -nopgbrk ./mydir/40_R4_saiwaicho.pdf ./text/40_R4_saiwaicho.txt
pdftotext -raw -layout -nopgbrk ./mydir/78_R4_roppongi.pdf ./text/78_R4_roppongi.txt
pdftotext -raw -layout -nopgbrk ./mydir/106_R4_sakurajuji.pdf ./text/106_R4_sakurajuji.txt
pdftotext -raw -layout -nopgbrk ./mydir/57_R4_mimuro.pdf ./text/57_R4_mimuro.txt
pdftotext -raw -layout -nopgbrk ./mydir/39_R4_kyourin.pdf ./text/39_R4_kyourin.txt
pdftotext -raw -layout -nopgbrk ./mydir/113_R4_sanchaart.pdf ./text/113_R4_sanchaart.txt
pdftotext -raw -layout -nopgbrk ./mydir/53_R4_shibakamiyama.pdf ./text/53_R4_shibakamiyama.txt
pdftotext -raw -layout -nopgbrk ./mydir/109_R4_kokubunji.pdf ./text/109_R4_kokubunji.txt
pdftotext -raw -layout -nopgbrk ./mydir/36_R4_usui.pdf ./text/36_R4_usui.txt
pdftotext -raw -layout -nopgbrk ./mydir/17_R4_nichii.pdf ./text/17_R4_nichii.txt
pdftotext -raw -layout -nopgbrk ./mydir/20_R4_ikashika.pdf ./text/20_R4_ikashika.txt
pdftotext -raw -layout -nopgbrk ./mydir/16_R4_kato.pdf ./text/16_R4_kato.txt
pdftotext -raw -layout -nopgbrk ./mydir/97_R4_akihabara.pdf ./text/97_R4_akihabara.txt
pdftotext -raw -layout -nopgbrk ./mydir/94_R4_azabu.pdf ./text/94_R4_azabu.txt
pdftotext -raw -layout -nopgbrk ./mydir/107_R4_Asada9gou.pdf ./text/107_R4_Asada9gou.txt
pdftotext -raw -layout -nopgbrk ./mydir/69_R4_hiroi.pdf ./text/69_R4_hiroi.txt
pdftotext -raw -layout -nopgbrk ./mydir/74_R4_shinjukuart.pdf ./text/74_R4_shinjukuart.txt
pdftotext -raw -layout -nopgbrk ./mydir/29_R4_fatility.pdf ./text/29_R4_fatility.txt
pdftotext -raw -layout -nopgbrk ./mydir/79_R4_kyounoart-takanawa.pdf ./text/79_R4_kyounoart-takanawa.txt
pdftotext -raw -layout -nopgbrk ./mydir/6_R4_harune.pdf ./text/6_R4_harune.txt
pdftotext -raw -layout -nopgbrk ./mydir/65_R4_ezaki.pdf ./text/65_R4_ezaki.txt
pdftotext -raw -layout -nopgbrk ./mydir/45_R4_teikyo.pdf ./text/45_R4_teikyo.txt
pdftotext -raw -layout -nopgbrk ./mydir/59_tokuoka_20230701ver2.pdf ./text/59_tokuoka_20230701ver2.txt
pdftotext -raw -layout -nopgbrk ./mydir/76_R4_kaibara.pdf ./text/76_R4_kaibara.txt
pdftotext -raw -layout -nopgbrk ./mydir/60_R4_utsumiyasuko.pdf ./text/60_R4_utsumiyasuko.txt
pdftotext -raw -layout -nopgbrk ./mydir/25_R4_cinemaart.pdf ./text/25_R4_cinemaart.txt
pdftotext -raw -layout -nopgbrk ./mydir/84_R4_aidakibo.pdf ./text/84_R4_aidakibo.txt
pdftotext -raw -layout -nopgbrk ./mydir/82_R4_kusuhara.pdf ./text/82_R4_kusuhara.txt
pdftotext -raw -layout -nopgbrk ./mydir/18_R4_juntendou.pdf ./text/18_R4_juntendou.txt
pdftotext -raw -layout -nopgbrk ./mydir/107_R4_Asada10gou.pdf ./text/107_R4_Asada10gou.txt
pdftotext -raw -layout -nopgbrk ./mydir/8_R4_toranomon.pdf ./text/8_R4_toranomon.txt
pdftotext -raw -layout -nopgbrk ./mydir/93_R4_jounan.pdf ./text/93_R4_jounan.txt
pdftotext -raw -layout -nopgbrk ./mydir/73_R4_sugiyamamarunouchi.pdf ./text/73_R4_sugiyamamarunouchi.txt
pdftotext -raw -layout -nopgbrk ./mydir/28_R4_tokyohart.pdf ./text/28_R4_tokyohart.txt
pdftotext -raw -layout -nopgbrk ./mydir/9_R4_jikei.pdf ./text/9_R4_jikei.txt
pdftotext -raw -layout -nopgbrk ./mydir/15_R4_tokyojoshi.pdf ./text/15_R4_tokyojoshi.txt
pdftotext -raw -layout -nopgbrk ./mydir/119_R4_esset.pdf ./text/119_R4_esset.txt
pdftotext -raw -layout -nopgbrk ./mydir/107_Asada_besshi.pdf ./text/107_Asada_besshi.txt
pdftotext -raw -layout -nopgbrk ./mydir/89_R4_iwamoto.pdf ./text/89_R4_iwamoto.txt
pdftotext -raw -layout -nopgbrk ./mydir/34_R4_matsumoto.pdf ./text/34_R4_matsumoto.txt
pdftotext -raw -layout -nopgbrk ./mydir/42_R4_sugiyamashinjuku.pdf ./text/42_R4_sugiyamashinjuku.txt
pdftotext -raw -layout -nopgbrk ./mydir/85_R4_kokusaiiryou.pdf ./text/85_R4_kokusaiiryou.txt
pdftotext -raw -layout -nopgbrk ./mydir/104_R4_nihonbashi.pdf ./text/104_R4_nihonbashi.txt
pdftotext -raw -layout -nopgbrk ./mydir/102_R4_ginzakounotori.pdf ./text/102_R4_ginzakounotori.txt
pdftotext -raw -layout -nopgbrk ./mydir/35_R4_nichidaiitabashi.pdf ./text/35_R4_nichidaiitabashi.txt
pdftotext -raw -layout -nopgbrk ./mydir/77_R4_morozumi.pdf ./text/77_R4_morozumi.txt
pdftotext -raw -layout -nopgbrk ./mydir/62_R4_shinbashiyume.pdf ./text/62_R4_shinbashiyume.txt
pdftotext -raw -layout -nopgbrk ./mydir/72_R4_sanchawomens.pdf ./text/72_R4_sanchawomens.txt
pdftotext -raw -layout -nopgbrk ./mydir/98_R4_sakuranome.pdf ./text/98_R4_sakuranome.txt
pdftotext -raw -layout -nopgbrk ./mydir/101_R4_komachi.pdf ./text/101_R4_komachi.txt
pdftotext -raw -layout -nopgbrk ./mydir/66_R4_tokiwadai.pdf ./text/66_R4_tokiwadai.txt
pdftotext -raw -layout -nopgbrk ./mydir/117_R4_ebisutsuji.pdf ./text/117_R4_ebisutsuji.txt
pdftotext -raw -layout -nopgbrk ./mydir/38_R4_majima.pdf ./text/38_R4_majima.txt
pdftotext -raw -layout -nopgbrk ./mydir/67_R4_niji-ogikubo.pdf ./text/67_R4_niji-ogikubo.txt
pdftotext -raw -layout -nopgbrk ./mydir/49_R4_nakano.pdf ./text/49_R4_nakano.txt
pdftotext -raw -layout -nopgbrk ./mydir/68_R4_ikeshita.pdf ./text/68_R4_ikeshita.txt
pdftotext -raw -layout -nopgbrk ./mydir/30_R4_hara.pdf ./text/30_R4_hara.txt
pdftotext -raw -layout -nopgbrk ./mydir/12_R4_akasakamiyazaki.pdf ./text/12_R4_akasakamiyazaki.txt
pdftotext -raw -layout -nopgbrk ./mydir/23_R4_syouwa.pdf ./text/23_R4_syouwa.txt
pdftotext -raw -layout -nopgbrk ./mydir/46_R4_jinnno.pdf ./text/46_R4_jinnno.txt
pdftotext -raw -layout -nopgbrk ./mydir/92_R4_akasaka.pdf ./text/92_R4_akasaka.txt
pdftotext -raw -layout -nopgbrk ./mydir/47_R4_tohofujin.pdf ./text/47_R4_tohofujin.txt
pdftotext -raw -layout -nopgbrk ./mydir/13_R4_tokyoika.pdf ./text/13_R4_tokyoika.txt
pdftotext -raw -layout -nopgbrk ./mydir/48_R4_ginzasuzuran.pdf ./text/48_R4_ginzasuzuran.txt
pdftotext -raw -layout -nopgbrk ./mydir/90_R4_naturalart.pdf ./text/90_R4_naturalart.txt
pdftotext -raw -layout -nopgbrk ./mydir/24_R4_toho.pdf ./text/24_R4_toho.txt
pdftotext -raw -layout -nopgbrk ./mydir/54_R4_ooizumigakuen.pdf ./text/54_R4_ooizumigakuen.txt
pdftotext -raw -layout -nopgbrk ./mydir/10_R4_sannou.pdf ./text/10_R4_sannou.txt
